### ISSUE TITLE
Tubed not working: 403

### ISSUE THREAD

**Issue by lizbethmutterhunt** [anxdpanic/plugin.video.tubed#188]
Hi anxdpanic, 

got panic here after a while working like hell, my tubed plugin is telling me: [403] the request could not be completed because you have exceeded your quota!"

All I did was to make sleep-music for 10 hours and after this, I got this failure. BTW, the script you wrote isn't necessary anymore; it has been superb implemented. Then there was a sudden recall for just one search with one result, I already watched and since then, no matter of Xbian or LibreElec, I get this f* error!

What to do to not being limited by google? Need kodi-log? And the "normal" YT plugin doesn't, asks for quality and stoppes starting to play!
Lizbeth

**Comment by anxdpanic** [comment]
I'm aware of the issue, I am working through the quota increase request submission. Once I've completed that, I'm not sure how long the request process will take.

Appreciate patience with this issue, it is in the works. 👍

**Comment by lizbethmutterhunt** [comment]
hiya, 

I got a secret for it: disable "use alternative player" and it works here again! Yes we're working at old-fox google to get more and more adfree-users without payment!

**Comment by pitsi** [comment]
> hiya,
> 
> I got a secret for it: disable "use alternative player" and it works here again! Yes we're working at old-fox google to get more and more adfree-users without payment!

May I ask where that setting is? The addon is broken since March and I am about to remove it from all 3 of my systems and go back to that pita of creating api keys for the youtube one, because it simply does not work as intended.

**Comment by briantho** [comment]
Where is this setting? I need it too. Please help, as I cannot use this addon even after logging in with Google...

**Comment by pitsi** [comment]
He probably means the "support alternative player" option under youtube's advanced settings...
I have removed tubed from all my devices since my post here, because the update to 1.0.4 did not solve that major issue that still plagues the addon. And, as a user on kodi forums said, it is a real shame that a non working addon is hosted in the official kodi repo :(

**Comment by anxdpanic** [comment]
It's no more broken than the YouTube addon. If you have a working YouTube add-on, copy the `api-keys.json` from the YouTube `addon_data` folder to the Tubed `addon_data` folder then sign in to Tubed.

I haven't had time to complete the request for quota, and it's not going to overnight process. I also can't request quota for an add-on that is unused and not available, the quota needs to be used.

It's not the greatest situation, but it's not _broken_. Just inconvenient to migrate from YouTube, and I can't make personal api as _convenient_ as the YouTube add-on to avoid breaking TOS and failing quota request from the onset.

**Comment by briantho** [comment]
Ah ok, I understand. So I need to set up the YouTube addon for now, then I can copy the right keys. Got it. It's a true shame you "have to" provide these keys or sign in to Google. But I understand, it's a Google problem. At the same time how is it that apps like newpipe (android app) and smarttubenext (another good android app) can work without signing into Google?

**Comment by anxdpanic** [comment]
We don't have access to javascript which is a limiting factor in going another way. I'm always on the look out though :)

**Comment by pitsi** [comment]
The reason tubed was developed in the first place was to provide access to youtube WITHOUT the need for an api key, at least from the user's side. Am I correct on that? 
It was working as it should when it was first released, but I assume google blocked its built in api key since March, thus all that mess since then. Now it is broken, plain and simple.

So, if it fails on that key aspect, then why use it? If it needs an api key too, why prefer it over the original youtube addon? Does tubed provide some feature that youtube does not? Is it faster? If not, why use it.
And imho, you, as a dev, are waisting your time by maintainign 2 addons that now have identical functionality. No offence.

**Comment by anxdpanic** [comment]
The API keys are fine, just at quota which again is required for me to even start the next stage. 

It is faster, some different features, and facilitated an API module for other other add-ons to use as well. The maintenance is next to nothing, so I don't really see 30 minutes every now an then a waste in any form. Also, there are users who prefer it, myself included.

Then I also have to consider that Google could request the takedown of the YouTube add-on at any time, and then I'd be scrambling to replace it. This add-on doesn't suffer the same takedown risk, since care was taken to avoid breaking the Branding and API TOS. It's also been reviewed by the Google OAuth team, verifying none of their rules are broken as well.

Again, I'm sorry it's inconvenient. I wish I had more time to devote to the quota request currently, and the intention is 100% to work on that when time/priorities allow.

**Comment by pitsi** [comment]
Thank you for all the clarifications.

Please allow me a semi-offtopic question that I had posted a while ago in tubed's thread on kodi forums. Newpipe works as a youtube client by scraping youtube's web page, without the need for an api key. And the same happens with 2 scripts that I have come accross, ytfzf (by pystardust) and pipe-viewer (by trizen).
How feasible is it to create a kodi addon that does the same and completely eliminate api usage and thus the need for an api key?

**Comment by briantho** [comment]
I understand completely. To be honest though it's a lot of work to generate a key from the end user standpoint. I wish this process wasn't needed, or if it was simpler. Also, I have the keys generated now, but I'm having a bit of trouble. I'm following the video in the wiki, and I have successfully created a api_keys.json file under the YouTube app for Kodi. Next i click sign in under YouTube. It asks me to go to Google.com/device  and enter the code. I do that. I resign in to Google, then I receive a 403 error from google. Access denied. Can you tell me from the screenshot what I did wrong? Thanks. 
![IMG_20210925_222705](https://user-images.githubusercontent.com/3977205/134795369-7ad20585-2314-4ea2-a46a-7eb1c9f5ee5f.jpg)

**Comment by montvid** [comment]
Tubed not working because of the 403 error. This issue should be reopened. Signing in with personal account does not help. The youtube kodi plugin works.
